channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash_kernel
  - snakemake
  - fastqc
  - multiqc
  - pip:
    - jupyterlab==3.1.0b0
    - jupyterlab-link-share
    - git+https://github.com/QuantStack/jupyterlab-drawio.git@rtc-using-string
